version: '3'
services:
  mysql:
    build: ./build/db/
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sqlconfig/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3006:3306
    platform: linux/amd64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=Asia/Tokyo
  api:
    build: ./build/go/
    tty: true
    volumes:
      - ./api:/go/src/api
      - ./credential:/go/src/api/credential
    ports:
      - '8080:8080'
    env_file:
      - authenv.env
volumes:
  mysql-data:
